name: Mobile App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Configurar Java (JDK 17)
        # Si cambiamos el JDK a otro actualizaríamos esta sección. 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: 3. Dar permisos al ejecutor (gradlew)
        # Esto es lo que permite que el Robot ejecute el script
        run: chmod +x gradlew

      - name: 4. Análisis estático (Lint)
        # Esto revisa errores de diseño, bugs potenciales y mejores prácticas
        run: ./gradlew lintDebug

      - name: 5. Ejecutar Tests Unitarios
        # Esto corre los tests de lógica que tengáis en la carpeta test/
        # Si no hay este paso ..
        run: ./gradlew testDebugUnitTest

      - name: 6. Build de verificación (Assemble)
        # Este paso intenta generar el APK de debug. 
        # Si hay un error de compilación en Kotlin o Compose, aquí fallará.
        run: ./gradlew assembleDebug